var tests = [{
  name: "Attribution",
  path: "./attribution/popcorn.attribution.unit.html",
  type: "Plugin"
}, {
  name: "DocumentCloud",
  path: "./documentcloud/popcorn.documentcloud.unit.html",
  type: "Plugin"
}, {
  name: "Flickr",
  path: "./flickr/popcorn.flickr.unit.html",
  type: "Plugin"
}, {
  name: "GML",
  path: "./gml/popcorn.gml.unit.html",
  type: "Plugin"
}, {
  name: "GoogleMap",
  path: "./googlemap/popcorn.googlemap.unit.html",
  type: "Plugin"
}, {
  name: "Rdio",
  path: "./rdio/popcorn.rdio.unit.html",
  type: "Plugin"
}, {
  name: "Linkedin",
  path: "./linkedin/popcorn.linkedin.unit.html",
  type: "Plugin"
}, {
  name: "TagThisPerson",
  path: "./tagthisperson/popcorn.tagthisperson.unit.html",
  type: "Plugin"
}, {
  name: "Tublr",
  path: "./tumblr/popcorn.tumblr.unit.html",
  type: "Plugin"
}, {
  name: "Mustache",
  path: "./mustache/popcorn.mustache.unit.html",
  type: "Plugin"
}, {
  name: "Pause",
  path: "./pause/popcorn.pause.unit.html",
  type: "Plugin"
}, {
  name: "Webpage",
  path: "./webpage/popcorn.webpage.unit.html",
  type: "Plugin"
}, {
  name: "WordRiver",
  path: "./wordriver/popcorn.wordriver.unit.html",
  type: "Plugin"
}, {
  name: "Code",
  path: "./code/popcorn.code.unit.html",
  type: "Plugin"
}, {
  name: "Facebook",
  path: "./facebook/popcorn.facebook.unit.html",
  type: "Plugin"
}, {
  name: "Footnote/Text",
  path: "./footnote/popcorn.footnote.unit.html",
  type: "Plugin"
}, {
  name: "Processing",
  path: "./processing/popcorn.processing.unit.html",
  type: "Plugin"
}, {
  name: "Subtitle",
  path: "./subtitle/popcorn.subtitle.unit.html",
  type: "Plugin"
}, {
  name: "Timeline",
  path: "./timeline/popcorn.timeline.unit.html",
  type: "Plugin"
}, {
  name: "Twitter",
  path: "./twitter/popcorn.twitter.unit.html",
  type: "Plugin"
}, {
  name: "Wikipedia",
  path: "./wikipedia/popcorn.wikipedia.unit.html",
  type: "Plugin"
}, {
  name: "GoogleFeed",
  path: "./googlefeed/popcorn.googlefeed.unit.html",
  type: "Plugin"
}, {
  name: "Image",
  path: "./image/popcorn.image.unit.html",
  type: "Plugin"
}, {
  name: "LastFM",
  path: "./lastfm/popcorn.lastfm.unit.html",
  type: "Plugin"
}, {
  name: "LowerThird",
  path: "./lowerthird/popcorn.lowerthird.unit.html",
  type: "Plugin"
}, {
  name: "OpenMap",
  path: "./openmap/popcorn.openmap.unit.html",
  type: "Plugin"
}

];